export const SET_LOCATION_SUGGESTS = 'SET_LOCATION_SUGGESTS'
export const SET_SELECTED_LOCATION = 'SET_SELECTED_LOCATION_DETAILS'
export const SET_FAVORITE_LOCATIONS = 'SET_FAVORITE_LOCATIONS'

export const TOGGLE_TEMPERATURE_UNIT = 'TOGGLE_TEMPERATURE_UNIT'