export const SET_LOCATION_SUGGESTS = 'SET_LOCATION_SUGGESTS'

export const SET_SELECTED_LOCATION_DETAILS = 'SET_SELECTED_LOCATION_DETAILS'
export const SET_SELECTED_LOCATION_CURRENT_WEATHER = 'SET_LOCATION_CURRENT_WEATHER'
export const SET_SELECTED_LOCATION_WEEKLY_FORCAST = 'SET_SELECTED_LOCATION_WEEKLY_FORCAST'